### ISSUE TITLE
Placing the links to wiki pages for assignment 2 onto project homepage

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2016group12#16]
After having completed the wiki pages for the assignment 2, we shouldn't forget about putting the links to the pages on our project homepage, as requested in the assignment.

**Comment by fepersembe** [comment]
I completed it.

**Comment by ThoAppelsin** [comment]
I am not sure whether this is really complete. The last sentence of the assignment reads: "Place links to the wiki pages on your github homepage." I might be wrong, but I think our instructor might be talking about this page instead: https://github.com/bounswe/bounswe2016group12

**Comment by fepersembe** [comment]
Yes, she is talking about exactly that page, but she says "Links to Wiki Pages". We have it. Plurality means that, every group should do that. If you agree with me, close it or we will talk tomorrow.
