### ISSUE TITLE
Assignment 5 - Peer Review for Group 8

### ISSUE THREAD

**Issue by Fzaero** [bounswe/bounswe2016group12#18]
[Use Case 6:](https://github.com/bounswe/bounswe2016group8/wiki/Use%20Cases)

1.  I think Use case 6 have necessary requirements, only I think of was maybe we could add another post condition which is topic will be recommended to students who viewed topics with similar tags, maybe to students who viewed other topics of same teacher or followed the teacher.

1.  Also may be something could be added to preconditions about teacher reputation.( Teacher who have been reported a lot could be stopped from adding new content maybe) 

[Sequence Diagram 3:](https://github.com/bounswe/bounswe2016group8/wiki/Sequence%20Diagram)

1. Class names maybe could be make better( Gui to Gui::SearchTab, application to maybe Topic::Search)
1. There are 2 found(topics), maybe one of them could be changed to some error code.
1. I think arrows between user and gui doesn't have to be synchronus.

[Activity Diagram (1,3,4):](https://github.com/bounswe/bounswe2016group8/wiki/Activity%20Diagram)

- Diagram1:
  1. I think teacher shouldn't be completely seperated from student. Teacher should be able to do everything student can do(view topics and search topics are must have for teacher).

- Diagram3:
  1. I think no result arrow should also exit the system with some action like "no topics found" .

- Diagram4:
  1. I think "Exit" transition should be added with an action"exit topic", and other transitions should return the start (since we may wish to continue viewing topic).

[Class Diagram:](https://github.com/bounswe/bounswe2016group8/wiki/Class%20Diagram)

1. Maybe a class can be added for broadcasts and digests.

1. Maybe timestamps could be added for logging

**Comment by ktasyaran** [comment]
[Class Diagram](https://github.com/bounswe/bounswe2016group8/wiki/Class%20Diagram)
