### ISSUE TITLE
Assignment 5 - Peer Review for Group 8

### ISSUE THREAD

**Issue by ktasyaran** [bounswe/bounswe2016group12#19]

**Comment by ktasyaran** [comment]
[Class Diagram](https://github.com/bounswe/bounswe2016group8/wiki/Class%20Diagram)

I want to write my comments about the diagram but the writings are so small that I could not read. Therefore I cannot make any review.

**Comment by ozankep** [comment]
Hello, you can open diagrams in a new tab, 
class diagram link : https://camo.githubusercontent.com/ca9c395abe4c2d22874db016a9e9eb93beed6c61/687474703a2f2f692e696d6775722e636f6d2f6f55734a4d44582e706e67
