### ISSUE TITLE
Test plan Formatting

### ISSUE THREAD

**Issue by alpk** [bounswe/bounswe2016group12#51]
The steps in your test plan at (https://github.com/bounswe/bounswe2016group12/wiki/Test-Plans) does not have a tabular (table like) format. As they are, your plan cannot be used for user testing. 

You should have a table with the following fields.
Step #, Description, Data, Expected Result, Actual Result, Pass/Fail

When you start user testing, you will give this table to a user and they will fill the Actual Result and Pass/Fail fields.

**Comment by ThoAppelsin** [comment]
Changing the format as requested. Need information about what is meant by "Data" in order to include that on our table.

**Comment by ezgitek** [comment]
I guess he means "test data". 
e.g. In TC#1 Preconditions 2, Test data is "random valid email address", "random valid password".

**Comment by ThoAppelsin** [comment]
I have changed the overall formatting of the test plan. Then I have formatted half of the test scenarios to have their steps described on tables. My colleague Ezgi has kindly offered help. She will be carrying out the rest of the conversion process.

**Comment by ThoAppelsin** [comment]
Ezgi is finished with enhancing the rest. She also had to review some of the test cases, for which she attributed herself as the reviewer. I have reviewed the changes she made, and claim that the requested change has been accomplished.
