### ISSUE TITLE
Meet with the customer

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2016group12#58]
Make an appointment with the customer and discuss the revisions on project requirements. Document the meeting notes afterwards.

**Comment by ThoAppelsin** [comment]
Made the meeting today between 14:00 and 15:00. The meeting notes are to come!

**Comment by ThoAppelsin** [comment]
Notes for the meeting are up! You can find them over there: [Customer Meeting 2](Customer-meeting-2)

**Comment by fepersembe** [comment]
Django server will be given from assistants

**Comment by ThoAppelsin** [comment]
I find it inappropriate to re-open a closed issue, unless that issue was inappropriately closed. The customer meeting was indeed made, sealed with its corresponding meeting notes. If a similar but new issue arose, then create a new issue for that. This one has a milestone for the [Lesson on 29.09.2016](https://github.com/bounswe/bounswe2016group12/milestone/8), and it was complete on time although now it looks past due by 9 days.

I am taking the liberty to close this back.
