### ISSUE TITLE
Everyone can commit into 'master'.

### ISSUE THREAD

**Issue by fepersembe** [bounswe/bounswe2016group12#6]
What if somebody commits mistakenly to 'master'.

**Comment by ezgitek** [comment]
Can we close this issue now? @fepersembe

**Comment by fepersembe** [comment]
@ezgitek only administrator change that, this can be close by an administrator (assistants )

**Comment by ezgitek** [comment]
@fepersembe Oh ok, my bad.

**Comment by fepersembe** [comment]
Everyone is sensitive about that topic, and we have less than 2 months, so I am closing it.
