### ISSUE TITLE
Prepare the Project Plan

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2016group12#67]
We need to prepare our project plan with its tasks arranged around the milestones we have. We need to make it into a Gantt Chart. It would be awesome if we had some utility to define tasks with sub-tasks, too.

Unfortunately, this will be an issue past due its milestone from the very beginning.

**Comment by fepersembe** [comment]
There is a software called GanttProject, It is useful than ProjectLibre, so if we can decide which milestone has which task, I can generate the gantt chart and plan as XLS and PDF.

**Comment by fepersembe** [comment]
@ThoAppelsin  I added this issue inside Meeting #10 Objectives, It must be discussed in detail.

**Comment by ThoAppelsin** [comment]
Thanks Furkan for his great find/suggestion: www.ganttpro.com provides a great web application for preparing a project plan in the form of a Gantt Chart. It's a more desirable option for being more responsive than its alternatives. And here's a sample of how it can export its charts into PDF, which will help us on showing it to our supervisors:

[MEANCO.pdf](https://github.com/bounswe/bounswe2016group12/files/520501/MEANCO.pdf)
