### ISSUE TITLE
Research templates for the Web Design

### ISSUE THREAD

**Issue by fepersembe** [bounswe/bounswe2016group12#70]
Using an easy-to-use template may speed up the work. 

Please share findings under this issue.

**Comment by heobu** [comment]
We could use [plot.ly](https://plot.ly/python/) for this. Especially the [Network Graph](https://plot.ly/python/3d-network-graph/) looks exactly like what we need. There's also [NetworkX](https://networkx.github.io) and that seems to come highly recommended as well. Additionally, there's [graph-tool](https://graph-tool.skewed.de) which apparently distinguishes itself from others by being implemented in C++ at its core with high performance in mind.

**Comment by iremzog** [comment]
We could use javascript library examples showed in the link: http://visjs.org/network_examples.html. Graph visualization in the example http://visjs.org/examples/network/exampleApplications/lesMiserables.html has a nice appearance.
