### ISSUE TITLE
Reorganize and restructure Wiki for easier navigation and editing

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2016group12#77]
Our Wiki is growing! Some of its sections have grown so large that they should better be split further into sub-subsections.

Aside from that, any group of items better be ordered lexicographically if there is no other obvious and intuitive order.

**Comment by ThoAppelsin** [comment]
Made many enhancements to the main Wiki page and to its sidebar. Added a new section in blockquotes called "New Stuff" for the recent additions, right on top of the main page.

**Comment by ezgitek** [comment]
See issue #129
