### ISSUE TITLE
Update the old web mockups with the new ones

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2016group12#78]
We have used some new mockups on our [Milestone Presentation](https://github.com/bounswe/bounswe2016group12/wiki/Milestone-Report-1). We reflect that update to the mockups we have on the Wiki: https://github.com/bounswe/bounswe2016group12/wiki/Mockups

**Comment by fepersembe** [comment]
Pull Request Merged,issue can be closed

**Comment by ThoAppelsin** [comment]
I have to reopen it, because the corresponding Wiki page is yet to be updated with the new images.

**Comment by ThoAppelsin** [comment]
Mockups with their stories are now up-to-date on [Wiki - Mockups](https://github.com/bounswe/bounswe2016group12/wiki/Mockups)!
