### ISSUE TITLE
Homework 2

### ISSUE THREAD

**Issue by ktasyaran** [bounswe/bounswe2016group12#9]
Watching the videos listed 

1. Scrum in Under 10 Minutes : https://www.youtube.com/watch?v=XU0llRltyFM
2. Patrick Lencioni: Five Dysfunctions Of a Team https://www.youtube.com/watch?v=6sqvWEI1CVg&spfreload=10

Optional videos:

1. Toyota Production System - 5S Just, Just in Time, Kaisen : https://www.youtube.com/watch?v=kce2L23yLcw 

2. Dan Pink: The puzzle of motivation : https://www.youtube.com/watch?v=rrkrvAUbU9Y

and making comments as described in the HW description

**Comment by fepersembe** [comment]
@ktasyaran link is not working now.
