### ISSUE TITLE
Prepare models.py on the Django project

### ISSUE THREAD

**Issue by ThoAppelsin** [bounswe/bounswe2016group12#90]
We need to prepare the models.py on our Django project, which will create the database tables for us when migrated! Cool, isn't it?

**Comment by caglabalcik** [comment]
Arkadaslar beni bu mail listesinden cikarirsaniz sevinirim. Ben yaptim
birkac kere ama duzelmiyor neden bilmiyorum.

Kolayliklar

2016-11-03 15:52 GMT+01:00 Utkan Gezer <notifications@github.com>:

**Comment by leventbas92** [comment]
Aynı şekilde beni de :)

**Comment by ThoAppelsin** [comment]
Çağla ve Levent, dediğinizi bizim yapmamız mümkün değil. Projenin Watchers listesinde yer alıyorsunuz. Listeyi şuradan görebilirsiniz:

https://github.com/bounswe/bounswe2016group12/watchers

Kendinizi listeden çıkarırsanız bildirim almazsınız diye düşünüyorum. Yukarıdaki "Unwatch" yazan butona basarak bir şeyler yapabilirsiniz diye umuyorum.

Hoşça kalın.

**Comment by ThoAppelsin** [comment]
Levent, sen ayrıca grup elemanları listesindeymişsin, seni gruptan attım.

Bunun dışında, ikinizin de Watchers listesinden çıkmış olduğunu görüyorum. Bu issue'ya cevap vermiş olmanızdan ötürü bu issue altına yazılan cevaplar için bildirim almaya devam ediyorsunuzdur diye tahmin ediyorum. En fazla 3-5 kez daha yazarız herhalde buranın altına, ancak eğer onları da istemiyorsanız, şu linki takip edin:

https://github.com/bounswe/bounswe2016group12/issues/90

... ve kendinizi sağ alt taraftaki Unsubscribe butonuyla bu issue'nun bildirim listesinden çıkarın.

**Comment by ThoAppelsin** [comment]
Models are up on the repository.
