### ISSUE TITLE
Make views and models more modular 

### ISSUE THREAD

**Issue by Fzaero** [bounswe/bounswe2016group12#93]
Make models and views folder and make necessary connection.

**Comment by ThoAppelsin** [comment]
I gave up on making the models.py modular. I failed to resolve the errors that have occurred on the way. I've already spent a week on this, and don't really think it's that so necessary.

Close it whenever you're done with the views part.

**Comment by ThoAppelsin** [comment]
I tried some more and managed to do split the models.py into a models package of:

- profile.py
- topic.py
- tag.py
- comment.py
- relation.py

You may close it whenever the views part is over.

**Comment by ThoAppelsin** [comment]
Actually, I see that the views part is already over, closing this.
